export const countries = {
	méxico: 'mx',
	'corea del sur': 'kr',
	canadá: 'ca',
	'estados unidos': 'us',
	qatar: 'qa',
	brasil: 'br',
	haití: 'ht',
	australia: 'au',
	alemania: 'de',
	'países bajos': 'nl',
	'costa de marfil': 'ci',
	suecia: 'se',
	españa: 'es',
	bélgica: 'be',
	'arabia saudita': 'sa',
	irán: 'ir',
	francia: 'fr',
	irak: 'iq',
	argentina: 'ar',
	austria: 'at',
	portugal: 'pt',
	inglaterra: 'gb-eng',
	ghana: 'gh',
	uzbekistán: 'uz',
	sudáfrica: 'za',
	bosnia: 'ba',
	escocia: 'gb-sct',
	turquia: 'tr',
	turquía: 'tr',
	ecuador: 'ec',
	túnez: 'tn',
	uruguay: 'uy',
	'nueva zelanda': 'nz',
	noruega: 'no',
	jordania: 'jo',
	panamá: 'pa',
	colombia: 'co',
	suiza: 'ch',
	marruecos: 'ma',
	'rep. checa': 'cz',
	'rep checa': 'cz',
	'república checa': 'cz',
	curazao: 'cw',
	curaçao: 'cw',
	japón: 'jp',
	paraguay: 'py',
	senegal: 'sn',
	'cabo verde': 'cv',
	egipto: 'eg',
	croacia: 'hr',
	'rd congo': 'cd',
	argelia: 'dz',
};
