export const mapCountries = new Map([
	['Mexico', 'MÉXICO'],
	['South Africa', 'SUDÁFRICA'],
	['South Korea', 'COREA DEL SUR'],
	['Czechia', 'REP.CHECA'],
	['Canada', 'CANADÁ'],
	['Bosnia-Herzegovina', 'BOSNIA'],
	['United States', 'ESTADOS UNIDOS'],
	['Paraguay', 'PARAGUAY'],
	['Qatar', 'QATAR'],
	['Switzerland', 'SUIZA'],
	['Brazil', 'BRASIL'],
	['Morocco', 'MARRUECOS'],
	['Scotland', 'ESCOCIA'],
	['Haiti', 'HAITÍ'],
	['Australia', 'AUSTRALIA'],
	['Türkiye', 'TURQUIA'],
	['Germany', 'ALEMANIA'],
	['Curaçao', 'CURAZAO'],
	['Netherlands', 'PAÍSES BAJOS'],
	['Japan', 'JAPÓN'],
	['Ivory Coast', 'COSTA DE MARFIL'],
	['Ecuador', 'ECUADOR'],
	['Sweden', 'SUECIA'],
	['Tunisia', 'TÚNEZ'],
	['Spain', 'ESPAÑA'],
	['Cape Verde', 'CABO VERDE'],
	['Belgium', 'BÉLGICA'],
	['Egypt', 'EGIPTO'],
	['Saudi Arabia', 'ARABIA SAUDITA'],
	['Uruguay', 'URUGUAY'],
	['Iran', 'IRÁN'],
	['New Zealand', 'NUEVA ZELANDA'],
	['France', 'FRANCIA'],
	['Senegal', 'SENEGAL'],
	['Iraq', 'IRAK'],
	['Norway', 'NORUEGA'],
	['Argentina', 'ARGENTINA'],
	['Algeria', 'ARGELIA'],
	['Austria', 'AUSTRIA'],
	['Jordan', 'JORDANIA'],
	['Portugal', 'PORTUGAL'],
	['Congo DR', 'RD CONGO'],
	['England', 'INGLATERRA'],
	['Croatia', 'CROACIA'],
	['Ghana', 'GHANA'],
	['Panama', 'PANAMÁ'],
	['Uzbekistan', 'UZBEKISTÁN'],
	['Colombia', 'COLOMBIA'],
]);
